# Generated by Django 5.2.10 on 2026-02-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('gtfs', '0004_remove_route_agency_id_legacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional user notes or details'),
        ),
        migrations.AddField(
            model_name='observation',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Trip this observation is about (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.trip'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stop',
            field=models.ForeignKey(blank=True, help_text='Stop where observation was made', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.stop'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('WAITING', 'Waiting at Stop'), ('ON_BUS', 'On Bus'), ('PASSED', 'Bus Passed'), ('ARRIVED', 'Bus Arrived'), ('NO_SHOW', "Bus Didn't Come"), ('REROUTED', 'Bus Rerouted'), ('BREAKDOWN', 'Bus Breakdown'), ('HEARTBEAT', 'Still on Bus (Heartbeat)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['trip', 'timestamp'], name='evidence_ob_trip_id_0bb55d_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['stop', 'timestamp'], name='evidence_ob_stop_id_49343b_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['user_id', 'timestamp'], name='evidence_ob_user_id_47ff1a_idx'),
        ),
    ]
