# Generated by Django 5.2.10 on 2026-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_observation_options_observation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='distance_from_trip',
            field=models.FloatField(blank=True, help_text="Meters from the linked trip's shape", null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='is_deviation',
            field=models.BooleanField(default=False, help_text='True if distance > 200m'),
        ),
    ]
