# Generated by Django 5.2.10 on 2026-01-19 17:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=255)),
                ('agency_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_id', models.CharField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='gtfs.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.trip')),
            ],
            options={
                'ordering': ['stop_sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='unique_trip_sequence')],
            },
        ),
    ]
