# Generated by Django 5.2.10 on 2026-02-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='direction_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='headed_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
