# Generated by Django 5.2.10 on 2026-02-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0002_remove_trip_direction_id_trip_headed_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('timezone', models.CharField(help_text="IANA timezone (e.g., 'Asia/Kolkata')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.RenameField(
            model_name='route',
            old_name='agency_id',
            new_name='agency_id_legacy',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='arrival_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds since 00:00:00 of service day (can exceed 86400 for late-night trips)', null=True),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='departure_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds since 00:00:00 of service day', null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gtfs.agency'),
            preserve_default=False,
        ),
    ]
