# Generated by Django 5.2.10 on 2026-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0003_agency_rename_agency_id_route_agency_id_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='agency_id_legacy',
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='departure_time',
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_seconds',
            field=models.IntegerField(help_text='Seconds since 00:00:00 of service day (can exceed 86400 for late-night trips)'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_seconds',
            field=models.IntegerField(help_text='Seconds since 00:00:00 of service day'),
        ),
    ]
