# Generated by Django 5.2.10 on 2026-02-09 10:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0004_remove_route_agency_id_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('shape_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='shape_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='gtfs.shape'),
        ),
    ]
