# Generated by Django 5.2.10 on 2026-01-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_trip', to='gtfs.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_stop_sequence', models.IntegerField()),
                ('progress_ratio', models.FloatField(default=0.0)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='realtime.activetrip')),
            ],
        ),
    ]
