# Generated by Django 5.2.10 on 2026-02-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0004_remove_route_agency_id_legacy_and_more'),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDelayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Service date for this delay record')),
                ('avg_delay_seconds', models.IntegerField(help_text='Average delay across all observations')),
                ('num_observations', models.IntegerField(help_text='Number of observations used in average')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_history', to='gtfs.trip')),
            ],
            options={
                'verbose_name_plural': 'Trip Delay Histories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trip', 'date'], name='realtime_tr_trip_id_74d098_idx')],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
